### ISSUE TITLE
TBSync EAS Stopped working with O365

### ISSUE THREAD

**Issue by erwdavid** [jobisoft/EAS-4-TbSync#218]
## Your environment

TbSync version: 4.3
EAS-4-TbSync version: 4.1.5
Thunderbird version: 102.7.1

## Expected behavior
Connects to O365 account provided by my employer

## Actual behavior
Error (translated from french)
OAuth2.0 authentication server returned {}

When trying to setup account on another profile, I get an error that "undefined is an unknown address"

## Steps to reproduce
Just  try connecting

To help resolving your issue, enable debug logging (TbSync Account Manager -> Help) and send me the debug.log via e-mail (use the title of your issue as subject of the email).

**Comment by UserX404** [comment]
I fixed this by rolling back TB to 102.6.
Read about there is a known bug with 102.7.

**Comment by erwdavid** [comment]
The bug in 102.7 was corrected by 102.7.1 and Thunderbird authenticates correctly. I do not know whether the changes in thunderbird may have changed something for TBSync EAS. I'll go back to 102.6 as a workaround.

**Comment by fgo-stei** [comment]
102.7.1 Did not solve the issue with TbSync, only the issue with Thunderbird
I had to roll back to 102.6.1 to get TbSync working again

**Comment by jobisoft** [comment]
https://github.com/jobisoft/EAS-4-TbSync/issues/215#issuecomment-1416725608
